CREATE TABLE `registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registrationNumber` varchar(32) NOT NULL,
	`playerTitle` varchar(24) NOT NULL,
	`playerFirstName` varchar(100) NOT NULL,
	`playerLastName` varchar(100) NOT NULL,
	`dateOfBirth` varchar(10) NOT NULL,
	`placeOfBirth` varchar(120) NOT NULL,
	`ageGroup` enum('U7','U9','U11','U13') NOT NULL,
	`address` text NOT NULL,
	`guardianName` varchar(180) NOT NULL,
	`guardianRelation` varchar(60) NOT NULL,
	`guardianPhone` varchar(32) NOT NULL,
	`guardianPhone2` varchar(32),
	`hasHealthIssue` boolean NOT NULL DEFAULT false,
	`healthDetails` text,
	`birthCertificate` boolean NOT NULL DEFAULT false,
	`medicalCertificate` boolean NOT NULL DEFAULT false,
	`photos` boolean NOT NULL DEFAULT false,
	`guardianIdCopy` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `registrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `registrations_registrationNumber_unique` UNIQUE(`registrationNumber`)
);
